name: Update counter

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
  push:
    paths:
      - 'count.json'

jobs:
  update-counter:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update views count
      run: |
        COUNT=$(jq '.count += 1' count.json)
        echo "$COUNT" > count.json

        VALUE=$(jq '.count' count.json)
        echo "<svg xmlns='http://www.w3.org/2000/svg' width='120' height='20'>" > views.svg
        echo "<rect width='120' height='20' fill='white'/>" >> views.svg
        echo "<text x='10' y='15' fill='black' font-family='Arial' font-size='14'>Views: $VALUE</text>" >> views.svg
        echo "</svg>" >> views.svg

    - name: Commit and push
      run: |
        git config user.name ${{ secrets.UPDATE_COUNTER_NAME }}
        git config user.email ${{ secrets.UPDATE_COUNTER_EMAIL }}
        git add count.json views.svg
        git commit -m "Update views count"
        git push
